import { makeStyles } from '@material-ui/core/styles';

export const useComparisonPageStyles = makeStyles({
  root: {
    backgroundColor: '#FFFFFF',
    minHeight: '100vh',
    overflow: 'visible',
    position: 'relative',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: '12px 0',
  },
  titleSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    '& .save-icon': {
      cursor: 'pointer',
    },
    '& .titleText': {
      fontSize: '20px',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: '24px',
    },
  },
  actionButtons: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '12px',
  },
  iconButtons: {
    backgroundColor: '#F4F6FA',
    color: '#1E232E',
    textTransform: 'none',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '150%',
    boxShadow: 'none',
    display: 'flex',
    padding: '8px 12px',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: '8px',
    borderRadius: '6px',
    '&:hover': {
      backgroundColor: '#F4F6FA',
      boxShadow: 'none',
    },
  },
  cardContainer: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    overflow: 'auto',
    flexWrap: 'nowrap',
    minHeight: '200px',
    paddingBottom: '8px',
  },
  cardItem: {
    boxSizing: 'border-box',
    flex: 1,
    minWidth: '456px',
  },
  addButton: {
    color: '#1D5ED8',
    backgroundColor: '#EFF5FF',
    borderColor: '#dfe1e5',
    textTransform: 'none',
    fontSize: '15px',
    fontWeight: 500,
    padding: '8px 24px',
    height: '40px',
    border: '0px',
    '&:hover': {
      backgroundColor: '#EFF5FF',
    },
  },
  compareButton: {
    backgroundColor: '#1D5ED8',
    fontSize: '15px',
    textTransform: 'none',
    padding: '8px 24px',
    height: '40px',
    fontWeight: 500,
    color: '#FFFFFF',
    '&:hover': {
      backgroundColor: '#1D5ED8',
    },
  },
  buttonGroup: {
    display: 'flex',
    gap: 12,
    justifyContent: 'flex-end',
    marginTop: '10px',
    marginBottom: '10px',
  },
  menuPaper: {
    maxWidth: '320px',
    width: '100%',
    overflow: 'visible',
    zIndex: 1,
    marginRight: '24px',
    backgroundColor: '#FFFFFF',
    boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.2)',
    marginTop: '8px',
    transform: 'translateX(-22px) !important',
  },
  menuList: {
    padding: 0,
  },
});

/** Inline styles for DCC chart overlays and dialogs (used in dcc-details page). */
export const dccStylesSx = {
  chartLoadingOverlaySx: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  chartLoadingContentSx: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '12px',
  },
  chartErrorOverlaySx: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    border: '1px solid #EAEDF6',
    height: '467px',
  },
  closeIconSx: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 24,
    height: 24,
    cursor: 'pointer',
    zIndex: 1,
  },
  chartErrorContentSx: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
  },
  chartErrorTitleSx: {
    fontSize: '20px',
    color: '#1E232E',
    fontWeight: 600,
    marginBottom: 6,
  },
  unsavedFiltersDialogPaperSx: {
    borderRadius: '12px',
    maxWidth: '560px',
    width: '480px',
  },
  unsavedFiltersDialogTitleSx: {
    color: '#3A4245',
    fontSize: '20px',
    fontWeight: 600,
    padding: '24px 24px 8px 24px',
  },
  unsavedFiltersDialogContentSx: {
    padding: '0px 24px 24px 24px',
  },
  unsavedFiltersDialogContentTextSx: {
    color: '#51585B',
    fontSize: '16px',
    lineHeight: '20px',
  },
  unsavedFiltersDialogActionsSx: {
    padding: '12px 24px 24px 24px',
    justifyContent: 'flex-end',
    gap: '12px',
  },
  unsavedFiltersSecondaryButtonSx: {
    backgroundColor: '#EFF5FF',
    color: '#1D5ED8',
    borderRadius: '6px',
    padding: '12px 24px',
    textTransform: 'none',
    fontSize: '16px',
    fontWeight: 500,
  },
  unsavedFiltersPrimaryButtonSx: {
    backgroundColor: '#1D5ED8',
    color: '#FFFFFF',
    borderRadius: '6px',
    padding: '12px 24px',
    textTransform: 'none',
    fontSize: '16px',
    fontWeight: 500,
    '&:hover': {
      backgroundColor: '#1D5ED8',
    },
  },
};
