/**
 * Vendored from AWB `utils/FilterConfig/dashboardFilterConfig.js` (`groupByTabConfig`).
 * Account group extended with toolbar / custom filters so `getAppliedFilterGroup` matches chrome.
 */
export const groupByTabConfig = {
  Location: ['City', 'State', 'Zip Code'],
  Account: [
    'Premise Type',
    'Meter Type',
    'Fuel Type',
    'Consumption Select',
    'User ID Type Filter',
    'User ID Filter Values',
    'User Status',
    'Rate Plan',
    'Annual Clusters',
    'Seasonal Cluster',
    'Daily Cluster',
    'Area Median Income (Census)',
  ],
  Premise: ['Home Type', 'Home Size', 'Home Ownership', 'Year Built'],
  'Appliance Targeting': [
    'Always On Ownership',
    'Cooking Ownership',
    'EV Ownership',
    'Lighting Ownership',
    'Pool Pump Ownership',
    'Refrigerator Ownership',
    'Heating Ownership',
    'Cooling Ownership',
    'Water Heater Ownership',
    'Anomalous Load Ownership',
    'Operational Load Ownership',
    'Base Load Ownership',
    'Solar Ownership',
    'Cooling Degradation',
    'Heating Degradation',
    'Cooling Saturation',
    'Heating Saturation',
    'Cooling Short Cycling Range',
    'Heating Short Cycling Range',
    'Heating Fuel Type',
    'Heating Efficiency',
    'Cooling Efficiency',
    'Pool Pump Type',
    'Pool Pump Amplitude',
    'Pool Pump Runs',
    'Heat Pump Ownership',
    'Water Heater Type',
    'Water Heater Rating',
    'Water Heater Runs',
    'Solar Capacity',
  ],
  'Load Research': [
    'Appliance Name',
    'Month Name',
    'Year',
    'Day of Month',
    'Hour of Day',
    'Day of Week',
    'Consumption Decile',
    'Consumption Histogram',
  ],
  'EV Analytics': [
    'Charger Type',
    'EV Likelihood',
    'EV Detection Likelihood',
    'EV Session Start Hour',
    'EV Session Start Day of Week',
    'Median Weekly Session Count',
    'Median Weekly Charging Duration (Hrs)',
    'Charger Amplitude',
  ],
  'Grid Assets': [
    'Upstream Substation',
    'Upstream Feeder',
    'Substation',
    'Feeder',
    'Transformer',
    'Peak Hours',
  ],
  Custom: [
    'Upload Chart Segment',
    'Custom Chart 1',
    'Custom Chart 2',
    'Custom Chart 3',
    'Custom Chart 4',
    'Custom Chart 5',
    'Custom Chart 6',
    'Custom Chart 7',
    'Custom Chart 8',
    'Custom Chart 9',
    'Custom Chart 10',
  ],
};
