/** Vendored from AWB `constants/index.js` (`NON_CHART_FILTERS_LIST`) — filter toolbar count. */
export const NON_CHART_FILTERS_LIST = [
  'Premise Type',
  'Meter Type',
  'Fuel Type',
  'Timeframe',
  'Dashboard Select',
  'Consumption Select',
  'Temperature Select',
  'Temperature Filter',
  'Dynamic Capacity',
  'Time Select',
  ' Substation',
  ' Feeder',
  ' Transformer Number',
  'Peak hour',
  'Cooling %',
  'WH %',
  'Heating %',
  'EV %',
  'PP %',
  'Group bubble chart by',
  'Max Demand',
  'Asset',
  'Details of Asset',
  'User ID Type Filter',
];
